import os

print("TELEGRAM_BOT_TOKEN=", os.getenv("TELEGRAM_BOT_TOKEN"))
print("FACEBOOK_PAGE_ID=", os.getenv("FACEBOOK_PAGE_ID"))
print("FACEBOOK_PAGE_ACCESS_TOKEN=", os.getenv("FACEBOOK_PAGE_ACCESS_TOKEN"))